---
abstract: 'Dochazka ATT system shared modules'
author:
  - 'Smithfarm <presnypreklad@gmail.com>'
build_requires:
  Params::Validate: '1.06'
  Test::Deep::NoTest: '0'
  Test::Fatal: '0'
configure_requires:
  Module::Build: '0.37'
  Software::License: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Dochazka-Common
provides:
  App::Dochazka::Common:
    file: lib/App/Dochazka/Common.pm
    version: '0.190'
  App::Dochazka::Common::Model:
    file: lib/App/Dochazka/Common/Model.pm
  App::Dochazka::Common::Model::Activity:
    file: lib/App/Dochazka/Common/Model/Activity.pm
  App::Dochazka::Common::Model::Employee:
    file: lib/App/Dochazka/Common/Model/Employee.pm
  App::Dochazka::Common::Model::Interval:
    file: lib/App/Dochazka/Common/Model/Interval.pm
  App::Dochazka::Common::Model::Lock:
    file: lib/App/Dochazka/Common/Model/Lock.pm
  App::Dochazka::Common::Model::Privhistory:
    file: lib/App/Dochazka/Common/Model/Privhistory.pm
  App::Dochazka::Common::Model::Schedhistory:
    file: lib/App/Dochazka/Common/Model/Schedhistory.pm
  App::Dochazka::Common::Model::Schedintvls:
    file: lib/App/Dochazka/Common/Model/Schedintvls.pm
  App::Dochazka::Common::Model::Schedule:
    file: lib/App/Dochazka/Common/Model/Schedule.pm
requires:
  Params::Validate: '1.06'
  Test::Deep::NoTest: '0'
  Time::Piece: '0'
  Time::Seconds: '0'
  perl: '5.012'
resources:
  homepage: https://sourceforge.net/projects/dochazka/
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: https://github.com/smithfarm/dochazka-common.git
version: '0.190'
